

final List<String> vehiclesGeneral = [
  'CAJA ABIERTA',
  'CAJA CERRADA',
  'MEDIA REDILA',
  'ESTACAS',
  'PLATAFORMA',
  'TANQUE DE ACERO INOXIDABLE GRADO ALIMENTICIO',
  'TANQUE DE ACERO NEGRO (AGUA TRATADA, AGUA POTABLE, ETC.)',
  'TANQUE DE ACERO INOXIDABLE GRADO ALIMENTICIO TERMO EJEMPLO VINO, MIEL, LECHE, ETC.',
  'VOLTEO',  'GONDOLA VOLTEO',

];

final List<String> vehiclesEspecializada = [
  'CAJA CERRADA O SECA (PARA MATERIALES PELIGROSOS)',
  'ESTACAS (PARA MATERIALES PELIGROSOS)',
  'PLATAFORMA (PARA MATERIALES PELIGROSOS)',
  'REDILAS (PARA MATERIALES PELIGROSOS)',
  'CABALLETE (TRANSPORTE DE VIDRIO)',
  'CAJA DE RECOLECCIÓN CON CARGADOR FRONTAL (BASURA Y/O CONTENEDORES)',
  'CAJA DE TRANSFERENCIA PARA BASURA',
  'CAJA O JAULA GANADERA PARA ANIMALES',
  'CAJA REFRIGERADA ',
  'CAMA BAJA O CUELLO GANSO PARA OBJETOS VOLUMINOSOS',
  'CHASIS PORTA CONTENEDOR ',
  'GÓNDOLA MADRINA (TRANSPORTE DE VEHÍCULOS SIN RODAR)',
  'GÓNDOLA PARA MINERALES, GRANOS ETC. A GRANEL VOLTEO',
  'PLATAFORMA CON GRÚA TELESCÓPICA AUXILIAR PARA MANIOBRAS DE CARGA Y DESCARGA',
  'PLATAFORMA ENCORTINADA',
  'TANQUE PARA DESEHOS, REMANENTES Y MATERIALES PELIGROSOS ACERO, INOXIDABLE, ACERO AL CARBON ETC. ',
  'TANQUE CON QUEMADORES CON CHAPOPOTEADEROS ASFALTO',
  'TOLVA PRESURIZADA (CEMENTO, GRANOS, MINERALES, ETC.)',
  'GONDOLA VOLTEO (MINERALES A GRENEL)',
  'PLATAFORMA ROLL OFF',
  'CAJA GANADERA',
  'CAJA MUDANCERA',
  'PLATAFORMA ENCORTINADA',
];


